id: I9B786F1D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:25:34+00:00'
last_modified: '2022-06-08T12:14:57.356028+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5285
  title: བོད་ཀྱི་སྐྱེས་ཆེན་དམ་པ་རྣམས་ཀྱི་རྣམ་ཐར་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6689':
      image_group_id: I3CN5287
      title: ''
      total_pages: 582
      order: 1
      base_file: 6689.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
